name: Build

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: brdgm/github-action-build@v1
        with:
          sonar-token: ${{ secrets.SONARCLOUD_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
