name: Release Drafter

on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: brdgm/github-action-release-drafter@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
